steps:
  # בניית ה-Scraper (נניח שזה מה שאתה רוצה להריץ קודם)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'me-west1-docker.pkg.dev/$PROJECT_ID/scraper-repo/scraper-api:latest', '-f', 'packages/scraper/Dockerfile', '.']

  # דחיפה לרישום
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'me-west1-docker.pkg.dev/$PROJECT_ID/scraper-repo/scraper-api:latest']

images:
  - 'me-west1-docker.pkg.dev/$PROJECT_ID/scraper-repo/scraper-api:latest'
